### PR TITLE
Created a user for testing purposes

### PR DESCRIPTION
**Pull request by perenchiod**

### CODE REVIEW

**Comment by perenchiod** [comment]
Hey man sorry i couldn't make it to class today i'll get as much work as i
can in today

**Comment by WavisDavis628** [comment]
es cool, I'm probably not even comming in, if you run into any conflicts
just take the files that are in conflict on ur cpu and put them somewhere
on ur desktop, delete the ones on the master and run 'git pull origin
master' then re add the files on your desktop and push it to dp and merge.
i'll set up a input and delete over the weekend.

**Comment by perenchiod** [comment]
alrighty

**Comment by WavisDavis628** [comment]
Hi MissingOneCharecte/M,

I'd like to add you to my professional network on LinkedIn.
- David

Confirm that you know David: https://www.linkedin.com/e/v2?e=0-ini9vp6f-6n&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=zQ1jJlmc&invitationId=6130922810152927232

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ini9vp6f-6n&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQHjmSNEQLp1FgAAAVRVp7d-fqARbt2XQ59pzEiTqAXAGGMoF11PJb4pcIURnF2q9WU-zzS7W8Nh3aCKJqNTDcs21Yj-ZN-1VPay4hMk7ruEUO1gB0bvwvgovXuy-JU5Qo2j4KksIfY9647gfVcTV68PudUZQ96jYsrH8NuFrLIjfGB6EPM3YTedLsC3sdthjX0F&eid=0-ini9vp6f-6n

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ini9vp6f-6n&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by WavisDavis628** [comment]
Hi Dylan,

The email address reply@reply.github.com was recently added to your LinkedIn account.

If you don&#39;t want that email associated with your account after all, here&#39;s how to remove it:

Type https://www.linkedin.com/e/v2?e=7d2trp-inib3wk6-wh&amp;t=nas&amp;midToken=AQFsKdGyicf2yQ&amp;ek=security_add_email_notification into your browser
Sign in with your email address and password
Find Primary email in the upper left and click Change/Add
Click Remove next to the email address you&#39;re removing.

Thanks for using LinkedIn and for helping us to keep your account secure.
The LinkedIn Team

This email was intended for Dylan Perenchio (PHP Developer at Visual Net Design LC). 
Learn why we included this: https://www.linkedin.com/e/v2?e=7d2trp-inib3wk6-wh&a=customerServiceUrl&midToken=AQFsKdGyicf2yQ&ek=security_add_email_notification&articleId=4788

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=7d2trp-inib3wk6-wh&a=customerServiceUrl&midToken=AQFsKdGyicf2yQ&ek=security_add_email_notification

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request closed without merging**
