### PR TITLE
commiting my work as of now

### PR DESCRIPTION
**Pull request by perenchiod**

### CODE REVIEW

**Comment by perenchiod** [comment]
crap another conflict

**Comment by WavisDavis628** [comment]
I'll fix it tmrw
I'ma leave early friday cuz i'm going to corpus

**Comment by WavisDavis628** [comment]
Hi MissingOneCharecte/M,

I'd like to add you to my professional network on LinkedIn.
- David

Confirm that you know David: https://www.linkedin.com/e/v2?e=0-ini9vp6x-qg&t=ssuw&tracking=eml-guest-invite-cta&ek=invite_guest&sharedKey=hH9sWXjY&invitationId=6130922808684924928

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ini9vp6x-qg&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQEAZqr9jQiqLgAAAVRVp7ntfDPAmcAyXhuD8iYI_0mXc-Kl5YlETvR6sMfUNmF7R8J1skfbu6tazp8e8-uiQ5gf1FixtjnvqQuwUce3NFFyuwH7F72arlX2-TA75S0CaZK-v2aN8ORufbbzdE8Kh9bjjP98vRt3B3sNAGQ0V5I_bUUYME-_rl28gke-caIELLkI&eid=0-ini9vp6x-qg

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ini9vp6x-qg&a=customerServiceUrl&ek=invite_guest

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Comment by WavisDavis628** [comment]
David Simonelli would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/e/v2?e=s85j06-inrvy2by-81&a=preRegInvite&ek=first_guest_reminder_01&li=14&m=hero&ts=accept_text&sharedKey=hH9sWXjY&invitationID=6130922808684924928

View David Simonelli&#39;s profile: https://www.linkedin.com/e/v2?e=s85j06-inrvy2by-81&a=preRegInvite&ek=first_guest_reminder_01&li=3&m=hero&ts=profile_text&sharedKey=hH9sWXjY&invitationID=6130922808684924928

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=s85j06-inrvy2by-81&t=lun&midToken=AQFmrFVhGEd36Q&ek=first_guest_reminder_01&li=16&m=unsub&ts=HTML&eid=s85j06-inrvy2by-81&loid=AQH6kGi0QRRPgAAAAVR5EJOBHxVEit57Z2pWqxARkq6Pe4GKbcbFyoEzlPXxAy6NXheeFNn1rKRWpNIMOdhvaFo6_U63ZrWqaaQg8Qxw0mCwMbIhhLLGqNY6DratF8CyxPe1LRKDCHD8OURYc12DG4m9s02JaI2Gb7xphwgj-0iGlDnNsJgEe6A0uSOBrjG2uUOc

This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=s85j06-inrvy2by-81&a=customerServiceUrl&ek=first_guest_reminder_01

&copy; 2016 LinkedIn Corporation, 2029 Stierlin Court, Mountain View CA 94043. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request closed without merging**
